### PR TITLE
Create strings.xml

### PR DESCRIPTION
**Pull request by Rakau**
Add Chinese translation

### CODE REVIEW

**Review by iboalali — APPROVED** [review]

**Comment by iboalali** [comment]
What kind of Chinese is it, Traditional, Simplified or Hong Kong?

screenshot_128

**Comment by Rakau** [comment]
Simplified

2017年11月6日 05:41，"Ibrahim Al-Alali" <notifications@github.com>写道：

**Comment by iboalali** [comment]
Thank you

**Comment by Rakau** [comment]
If I have time, I can also do traditional Chinese translation

2017年11月6日 07:20，"Ibrahim Al-Alali" <notifications@github.com>写道：

**Comment by iboalali** [comment]
If you want to, it will be awesome.

And how should I credit you? twitter, email or/and facebook? anything else?

**Comment by Rakau** [comment]
my twitter: @ljy_rakau

2017年11月6日 07:23，"Ibrahim Al-Alali" <notifications@github.com>写道：

**Pull request merged**
