### PR TITLE
Improve notification detection

### PR DESCRIPTION
**Pull request by mickael9**
The "running in the background" notification has an
"android.foregroundApps" extra that can be used to tell it apart from
other android system notifications, we can use that instead of matching
the notification title.

https://github.com/aosp-mirror/platform_frameworks_base/blob/master/services/core/java/com/android/server/am/ActiveServices.java#L887

### CODE REVIEW

**Comment by iboalali** [comment]
I will look into the "android.foregroundApps" extra

**Comment by iboalali** [comment]
You are right, it gives me all the apps that are running in the background and generate this system notification.
I will do some more tests on the new Pixel phones (the notification changed a little on these phones) and then I will merge your pull request.

**Comment by kapiladhikesavalu** [comment]
Hi, is this change going to help in removing access to notification?

**Comment by iboalali** [comment]
@kapiladhikesavalu no

**Pull request merged**
